'use client';

import React from 'react';
import { Card } from '@heroui/react';

export default function TermsPage() {
  return (
    <div className="flex-1 w-full bg-neutral-50/50 dark:bg-neutral-950 py-10 transition-colors duration-300">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 space-y-6">
        <h1 className="text-3xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50">
          Terms of Service
        </h1>
        <p className="text-xs text-neutral-400">Last updated: July 17, 2026</p>
        
        <Card className="p-6 border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-sm space-y-4 text-xs leading-relaxed text-neutral-600 dark:text-neutral-300">
          <p>
            Welcome to GreenPulse AI. These Terms of Service govern your use of our ESG intelligence platform, compliance trackers, and AI copilots.
          </p>

          <h2 className="text-sm font-bold text-neutral-900 dark:text-white pt-2">1. Acceptable Telemetry Reporting</h2>
          <p>
            Users represent that all logged carbon audits, billing inputs, and telemetry CSV datasets reflect actual utility receipts and energy footprints. Logging deceptive or fabricated compliance data is prohibited.
          </p>

          <h2 className="text-sm font-bold text-neutral-900 dark:text-white pt-2">2. System Usage Limits</h2>
          <p>
            AI OCR bill scanning and conversational copilot questions are bound by fair-use thresholds. We reserve the right to throttle sessions that flood LLM nodes to protect compute capacity for other compliance managers.
          </p>

          <h2 className="text-sm font-bold text-neutral-900 dark:text-white pt-2">3. Accuracy of AI Recommendations</h2>
          <p>
            Carbon scope splits, weekend anomalies flags, and building mitigation priorities are generated by foundation models. While highly optimized, these insights are for advisory use and should be verified by a certified LEED/compliance engineer before deployment.
          </p>
        </Card>
      </div>
    </div>
  );
}
